login authentication broken. close #13
Babywise/Restaurant-WebApp-ASP.NET pull request #26
Opened 2023-04-21 06:48 UTC by Babywise

Login now checks account type before allowing the user to enter the application.

2023-04-21 14:50 UTC, dsmith2304 requested changes
Please fix bugs 28, 29, 30 before I can approve this pull request ( or discuss tolerance in meeting )

2023-04-21 15:12 UTC, nickvprince approved these changes

2023-04-21 16:04 UTC, Babywise commented
bug fix for #29 fixed this bug as well, close #30

2023-04-22 02:53 UTC, dsmith2304 approved these changes

2023-04-22 03:02 UTC, merged